#pragma once

#include "rendering/backend/RenderDevice.h"

#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace Wayfinder
{
    class SlangCompiler;

    // ── Shader Variant System ────────────────────────────────

    // Bitmask of compile-time shader features.
    // Each bit corresponds to a #define passed to the shader compiler at build time.
    // Variant 0 is the base (no defines).
    using ShaderVariantKey = uint32_t;

    enum class ShaderFeature : uint32_t
    {
        None = 0,
        VertexColour = 1 << 0,
        AlphaTest = 1 << 1,
    };

    inline ShaderVariantKey operator|(ShaderFeature a, ShaderFeature b)
    {
        return static_cast<ShaderVariantKey>(a) | static_cast<ShaderVariantKey>(b);
    }

    /**
     * @brief Loads shader bytecode, resolves resource counts, and caches GPU shader handles.
     *
     * Resource counts are resolved from one of two sources (in priority order):
     * 1. Runtime Slang compilation path: Slang reflection from the compile result.
     * 2. Build-time manifest: shader_manifest.json generated by wayfinder_shader_manifest.
     */
    class WAYFINDER_API ShaderManager
    {
    public:
        ShaderManager() = default;
        ~ShaderManager() = default;

        ShaderManager(const ShaderManager&) = delete;
        ShaderManager& operator=(const ShaderManager&) = delete;

        void Initialise(RenderDevice& device, std::string_view shaderDirectory, SlangCompiler* compiler = nullptr);
        void Shutdown();

        /**
         * @brief Load a shader_manifest.json for pre-compiled resource count lookups.
         *
         * The manifest maps shader names to per-stage resource counts so that
         * Shipping builds (without runtime Slang) don't need to parse SPIR-V at load time.
         * @return true if the manifest was loaded successfully.
         */
        bool LoadManifest(std::string_view manifestPath);

        /**
         * @brief Invalidates all cached GPU shaders.
         *
         * Destroys every cached shader handle and clears the map.
         * The next GetShader() call will reload from .spv or recompile from .slang.
         * Callers must also invalidate pipelines that reference the old handles.
         */
        void ReloadShaders();

        GPUShaderHandle GetShader(std::string_view name, ShaderStage stage, ShaderVariantKey variant = 0);

        std::vector<uint8_t> LoadComputeShaderBytecode(std::string_view name);

    private:
        struct ShaderKey
        {
            std::string name;
            ShaderStage stage;
            ShaderVariantKey variant = 0;

            bool operator==(const ShaderKey& other) const
            {
                return name == other.name and stage == other.stage and variant == other.variant;
            }
        };

        struct ShaderKeyHash
        {
            size_t operator()(const ShaderKey& k) const
            {
                size_t h1 = std::hash<std::string>{}(k.name);
                size_t h2 = std::hash<uint8_t>{}(static_cast<uint8_t>(k.stage));
                size_t h3 = std::hash<uint32_t>{}(k.variant);
                return h1 ^ (h2 << 1) ^ (h3 << 2);
            }
        };

        [[nodiscard]] std::optional<ShaderResourceCounts> LookupManifest(std::string_view name, ShaderStage stage) const;
        static std::vector<uint8_t> ReadFile(const std::string& path);

        RenderDevice* m_device = nullptr;
        SlangCompiler* m_compiler = nullptr;
        std::string m_shaderDir;
        std::unordered_map<ShaderKey, GPUShaderHandle, ShaderKeyHash> m_cache;

        struct ManifestEntry
        {
            std::optional<ShaderResourceCounts> Vertex;
            std::optional<ShaderResourceCounts> Fragment;
        };
        std::unordered_map<std::string, ManifestEntry> m_manifest;
    };

} // namespace Wayfinder
